apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "porigins-server-cpp.fullname" . }}
  labels:
    {{- include "porigins-server-cpp.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
    {{- if eq .Values.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.deploymentStrategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.deploymentStrategy.rollingUpdate.maxSurge }}
    {{- end }}
  selector:
    matchLabels:
      {{- include "porigins-server-cpp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "porigins-server-cpp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "porigins-server-cpp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: login
              containerPort: {{ .Values.service.loginPort | default 7171 }}
              protocol: TCP
            - name: game
              containerPort: {{ .Values.service.gamePort | default 7172 }}
              protocol: TCP
            - name: status
              containerPort: {{ .Values.service.statusPort | default 7171 }}
              protocol: TCP
            {{- if .Values.service.adminPort }}
            - name: admin
              containerPort: {{ .Values.service.adminPort }}
              protocol: TCP
            {{- end }}
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "porigins-server-cpp.fullname" . }}-secret
                  key: mysql-password
            - name: MYSQL_HOST
              value: "{{ include "porigins-server-cpp.mysqlHost" . }}"
            - name: MYSQL_PORT
              value: "{{ include "porigins-server-cpp.mysqlPort" . }}"
            - name: MYSQL_DATABASE
              value: "{{ include "porigins-server-cpp.mysqlDatabase" . }}"
            - name: MYSQL_USER
              value: "{{ include "porigins-server-cpp.mysqlUser" . }}"
          volumeMounts:
            - name: config
              mountPath: /app/config.lua
              subPath: config.lua
              readOnly: true
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /app/data
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: login
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            tcpSocket:
              port: login
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "porigins-server-cpp.fullname" . }}-config
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "porigins-server-cpp.fullname" . }}-data
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
