apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: porigins-server-cpp-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DistTopic/porigins-server-cpp-infra
    targetRevision: main
    path: porigins-server-cpp-prod
    helm:
      valueFiles:
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: stable
  destination:
    server: https://kubernetes.default.svc
    namespace: porigins-server-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
