name: Update Image Version

on:
  repository_dispatch:
    types: [image-update]

jobs:
  update-image-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract image info
      id: extract
      run: |
        echo "image=${{ github.event.client_payload.image }}" >> $GITHUB_OUTPUT
        echo "tag=${{ github.event.client_payload.tag }}" >> $GITHUB_OUTPUT
        echo "sha=${{ github.event.client_payload.sha }}" >> $GITHUB_OUTPUT
        echo "repository=${{ github.event.client_payload.repository }}" >> $GITHUB_OUTPUT

    - name: Update image version files
      run: |
        # Create image version files
        mkdir -p image-versions
        
        # Update main version file
        cat > image-versions/latest.yaml << EOF
        image: ${{ steps.extract.outputs.image }}:${{ steps.extract.outputs.tag }}
        tag: ${{ steps.extract.outputs.tag }}
        sha: ${{ steps.extract.outputs.sha }}
        repository: ${{ steps.extract.outputs.repository }}
        updated_at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
        commit_url: "https://github.com/${{ steps.extract.outputs.repository }}/commit/${{ steps.extract.outputs.sha }}"
        EOF
        
        # Update development version if from main branch
        if [[ "${{ github.event.client_payload.ref }}" == "refs/heads/main" ]]; then
          cp image-versions/latest.yaml image-versions/dev.yaml
          
          # Update dev values
          sed -i 's/tag: .*/tag: dev-latest/' porigins-server-cpp-dev/values-dev.yaml || true
        fi
        
        # Update production version if it's a tag
        if [[ "${{ github.event.client_payload.ref }}" == refs/tags/* ]]; then
          cp image-versions/latest.yaml image-versions/stable.yaml
          
          # Update prod values  
          sed -i 's/tag: .*/tag: stable/' porigins-server-cpp-prod/values-prod.yaml || true
        fi

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add image-versions/
        git add porigins-server-cpp-*/values-*.yaml || true
        
        if git diff --staged --quiet; then
          echo "No changes to commit"
          exit 0
        fi
        
        git commit -m "feat: Update server image to ${{ steps.extract.outputs.tag }}
        
        - Image: ${{ steps.extract.outputs.image }}:${{ steps.extract.outputs.tag }}
        - Source commit: ${{ steps.extract.outputs.sha }}
        - Repository: ${{ steps.extract.outputs.repository }}
        - Updated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        
        git push
